plugins {
    id("com.android.application") version '8.13.2' apply false
    id("org.jetbrains.kotlin.android") version "2.3.10" apply false
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://jitpack.io'
            content {
                includeGroup 'com.github.dburckh'
            }
        }
    }
}

tasks.register('clean', Delete) {
    delete layout.buildDirectory
}
